Repository TeamSobokSobok/Sobok-Server, pull requests merged in 2022-08, with the labels that each got.

#176 Fix: 알림 리스트 전체 조회 시 sendGroupId값 추가
  functions/db/group.js
  functions/db/notice.js
  functions/service/noticeService.js
Labels: 👾 crayon, 🛠 refactor

#173 Refactor: 약 수정 및 중단 코드 리팩토링
  functions/api/routes/pill/deleteMyPillDELETE.js
  functions/api/routes/pill/index.js
  functions/api/routes/pill/pillByUserIdCountGET.js
  functions/api/routes/pill/pillCountGET.js
  functions/api/routes/pill/pillMemberByMemberIdPOST.js
  functions/api/routes/pill/pillModifyPUT.js
  functions/api/routes/pill/pillPOST.js
  functions/api/routes/pill/stopPillPUT.js
  functions/controller/pillController.js
  functions/db/schedule.js
  functions/service/pillService.js
  functions/service/scheduleService.js
Labels: 👾 crayon, 🛠 refactor

#179 Feat: 유저 닉네임 수정 api 구현
  functions/api/routes/user/index.js
  functions/constants/responseMessage.js
  functions/controller/authController.js
  functions/controller/userContoller.js
  functions/db/user.js
  functions/lib/nicknameVerify.js
  functions/service/authService.js
  functions/service/userService.js
Labels: 👾 crayon, 🎃 feat

#183 Fix: 약 수락시 약 추가 가능 여부 로직 추가
  functions/controller/noticeController.js
  functions/service/noticeService.js
  functions/service/pillService.js
Labels: 👾 crayon, 🛠 refactor

#181 Feat: 이벤트 발생 푸쉬알림 추가
  functions/constants/returnType.js
  functions/db/group.js
  functions/db/notice.js
  functions/db/sendPill.js
  functions/db/user.js
  functions/service/noticeService.js
  functions/service/pillService.js
Labels: 👾 crayon, 🎃 feat

#188 Refactor: response 데이터 수정
  functions/db/schedule.js
  functions/db/sticker.js
  functions/service/scheduleService.js
Labels: 👾 crayon, 🛠 refactor

#193 Refactor: 타인에게 받은 약 상세정보 데이터 추가
  functions/api/routes/notice/index.js
  functions/api/routes/notice/noticeListGET.js
  functions/api/routes/notice/pillInfoGET.js
  functions/api/routes/notice/pillInfoPUT.js
  functions/controller/noticeController.js
  functions/db/notice.js
  functions/db/pill.js
  functions/service/noticeService.js
Labels: 👾 crayon, 🛠 refactor

#203 Fix: 푸시알림 에러처리
  functions/service/noticeService.js
  functions/service/pillService.js
Labels: 👾 crayon, 🛠 refactor

#211 feat: 유저 정보 조회 API 추가
  functions/api/routes/user/index.js
  functions/constants/responseMessage.js
  functions/controller/userContoller.js
Labels: 🎃 feat
